[package]
name = "rmenu_service"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0.192", features = ["derive"] }
uuid = { version = "1.5.0", features = ["serde"] }
yew = "0.21.0"
yew-agent = "0.2.0"
