[package]
name = "tchatchers_async"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = { version = "0.15.0", default-features = false }
env_logger = "0.10.0"
log = "0.4.19"
serde = { version = "1.0.171", features = ["derive"] }
serde_yaml = { version = "0.9.22" }
tchatchers_core = { path = "../tchatchers_core" , features = ["async"] }
tokio = { version = "1.28.2", default-features = false, features = ["rt", "macros", "rt-multi-thread", "time"] }
