FROM rust:1.77.1-alpine as builder

WORKDIR /home/usr/tct/

COPY ./  ./

RUN apk add libressl-dev musl-dev upx

RUN cargo install --path ./tchatchers_cli_tools/ 

RUN upx --best --lzma /usr/local/cargo/bin/tct

FROM alpine:latest

WORKDIR /home/usr/tct/

COPY --from=builder /usr/local/cargo/bin/tct /usr/local/sbin/tct

RUN adduser -D runner && chown -R runner ./

RUN chmod 111 /usr/local/sbin/tct

USER runner

RUN ln -s /usr/local/sbin/tct /home/usr/tct/tct

ENTRYPOINT ["./tct"]
CMD ["./tct"]
