version: "3.9"
services:
  postgres:
    image: postgres:14
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-chatter}
      POSTGRES_DB: ${POSTGRES_DB:-chatapp}
  redis:
    image: redis:6.2.11-alpine
    restart: always
    volumes:
      - redis:/data
  back :
    image: nag763/tchatchers_back:latest
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-pg.tchatche.rs}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-chatapp}
      POSTGRES_USER: ${POSTGRES_USER:-chatter}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REDIS_HOST: ${REDIS_HOST:-redis.tchatche.rs}
      REDIS_PORT: ${REDIS_PORT:-6379}
    links:
      - postgres:${POSTGRES_HOST:-pg.tchatche.rs}
      - redis:${REDIS_HOST:-redis.tchatche.rs}
    depends_on:
      - postgres
    build: 
      context: ./ 
      dockerfile: Dockerfile_back
    volumes:
      - static:/home/usr/back/static
      - ./env:/home/usr/back/.env:ro
  doc:
    image: nag763/tchatchers_doc:latest
    build: 
      context: ./ 
      dockerfile: Dockerfile_doc
  front :
    image: nag763/tchatchers_front:latest
    volumes:
      - ${SSL_CERTIFICATE_PATH:-/dev/null}:/usr/nginx/home/certs/cert.crt:ro
      - ${SSL_CERTIFICATE_KEY:-/dev/null}:/usr/nginx/home/certs/key.pem:ro
      - ${SSL_DHPARAM_PATH:-/dev/null}:/usr/nginx/home/certs/ssl-dhparams.pem:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - back
      - doc
    links:
      - back:back.tchatche.rs
      - doc:doc.tchatche.rs
    build: 
      context: ./ 
      dockerfile: Dockerfile_front
    ports:
      - "80:80"
      - "443:443"
  cli :
    image: nag763/tchatchers_tct:latest
    volumes:
      - .env:/home/usr/tct/.env
    links:
      - postgres:${POSTGRES_HOST:-pg.tchatche.rs}
    depends_on:
      - postgres
    build: 
      context: ./ 
      dockerfile: Dockerfile_tct
volumes:
  db:
  static:
  redis:
