FROM rust:1.72.1-alpine as builder

WORKDIR /home/usr/async/

COPY ./ ./

RUN apk add libressl-dev musl-dev

RUN cargo install --path ./tchatchers_async/

FROM alpine:latest

WORKDIR /home/usr/async/

COPY --from=builder /usr/local/cargo/bin/tchatchers_async /home/usr/async/tchatchers_async

RUN adduser -D runner && chown -R runner ./

RUN chmod 111 /home/usr/async/tchatchers_async

USER runner

CMD RUST_LOG=INFO ./tchatchers_async
