FROM rust:1.66 as builder

WORKDIR /home/usr/back/

COPY tchatchers_back/ ./

COPY tchatchers_core/ ../tchatchers_core/

RUN cargo install --path .

FROM rust:1.66

WORKDIR /home/usr/back/

COPY --from=builder /usr/local/cargo/bin/tchatchers_back /usr/local/cargo/bin/tchatchers_back

COPY .env ./

RUN adduser runner && chown -R runner ./

RUN mkdir static

RUN chown -R runner static

RUN chmod 111 /usr/local/cargo/bin/tchatchers_back

RUN chmod 400 .env

USER runner

CMD RUST_LOG=tower_http=info tchatchers_back
