FROM rust:1.65 as builder

WORKDIR /home/usr/back/

COPY tchatchers_back/ ./

COPY tchatchers_core/ ../tchatchers_core/

RUN cargo install --path .

FROM rust:1.65

WORKDIR /home/usr/back/

COPY --from=builder /usr/local/cargo/bin/tchatchers_back /usr/local/cargo/bin/tchatchers_back

COPY .env ./

RUN adduser runner && chown -R runner ./

RUN chown -R runner /usr/home/back/static

RUN chmod 111 /usr/local/cargo/bin/tchatchers_back

RUN chmod 400 .env

USER runner

CMD tchatchers_back
