FROM node as asset_builder

WORKDIR /home/usr/front

COPY ./tchatchers_front/src ./src

COPY ./tchatchers_front/Cargo.toml ./Cargo.toml

COPY ./tchatchers_front/tailwind.config.js ./tailwind.config.js

COPY ./tchatchers_front/main.css ./main.css

COPY ./tchatchers_front/index.html ./index.html

COPY ./tchatchers_front/install_assets.sh ./install_assets.sh

RUN mkdir assets

RUN bash install_assets.sh

FROM rust:1.73 as src_builder

WORKDIR /usr/tchatchers/front

COPY --from=asset_builder /home/usr/front /usr/tchatchers/front

COPY --from=asset_builder /home/usr/front/assets /usr/tchatchers/front/release/assets

COPY ./tchatchers_core ../tchatchers_core

COPY ./tchatchers_front/services ./services

COPY ./tchatchers_front/favicon.ico ./release/favicon.ico

COPY ./tchatchers_front/assets/no_pfp.webp ./release/assets/no_pfp.webp

COPY ./tchatchers_front/pkg_rel.sh ./pkg_release.sh

COPY ./tchatchers_front/release/index.html ./release/index.html

COPY ./tchatchers_front/release/index.js ./release/index.js

RUN rustup target add wasm32-unknown-unknown

RUN cargo install wasm-pack

RUN bash pkg_release.sh --no-assets --no-copy

FROM node as compressor

WORKDIR /usr/tchatchers/dist

COPY --from=src_builder /usr/tchatchers/front/release /usr/tchatchers/dist

RUN npm install -g uglify-js

RUN for i in ./*.js; do uglifyjs $i --in-situ; done

RUN gzip -r ./*

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY --from=compressor /usr/tchatchers/dist /usr/share/nginx/html

COPY .git/refs/heads/main /usr/share/nginx/html/.rev

EXPOSE 80
