FROM rust:1.70-alpine as builder

WORKDIR /home/usr/tct/

COPY tchatchers_cli_tools/ ./

COPY tchatchers_core/ ../tchatchers_core/

RUN apk add libressl-dev musl-dev

RUN cargo install --path .

FROM rust:1.70-alpine

WORKDIR /home/usr/tct/

COPY --from=builder /usr/local/cargo/bin/tct /usr/local/cargo/bin/tct

RUN adduser -D runner && chown -R runner ./

RUN chmod 111 /usr/local/cargo/bin/tct

USER runner

ENTRYPOINT ["tct"]
