FROM rust:1.85.0 as doc_builder

WORKDIR /home/usr/doc

COPY ./ .

RUN cargo doc --no-deps --all-features --target-dir doc

FROM nginx:alpine-slim

COPY --from=doc_builder /home/usr/doc/doc/doc/ /usr/share/nginx/html/doc

EXPOSE 80
