- &contact:
  id: 5
  href: /contact
  label: contact_menu
  default_translation: Contact
  visibility: []
- &gdpr_and_privacy_notice:
  id: 5
  href: /gdpr
  label: gdpr_menu
  default_translation: GDPR and Privacy Notice
  visibility: []
- &sign_up:
  id: 4
  href: /signin
  label: sign_in
  default_translation: Settings
  visibility: []
- &sign_in:
  id: 3
  href: /signup
  label: sign_up
  default_translation: Log out
  visibility: []
- &settings:
  id: 2
  href: /settings
  label: settings_menu
  default_translation: Settings
  visibility: [User, Admin, Moderator]
- &logout:
  id: 1
  href: /logout
  label: logout_menu
  default_translation: Log out
  visibility: [User, Admin, Moderator]