[package]
name = "chat_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
gloo-console = "0.3.0"
gloo-net = "0.5.0"
js-sys = "0.3.68"
tchatchers_core = { version = "0.1.0", path = "../../../tchatchers_core", features = ["front"] }
wasm-bindgen-futures = "0.4.41"
web-sys = "0.3.68"
yew-agent = "0.2.0"
postcard = { version = "1.0.8", features = ["use-std"], default-features = false }