[package]
name = "chat_service"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
futures = "0.3.29"
gloo-console = "0.3.0"
gloo-net = "0.4.0"
js-sys = "0.3.65"
serde_json = "1.0.108"
tchatchers_core = { version = "0.1.0", path = "../../../tchatchers_core", features = ["front"] }
wasm-bindgen-futures = "0.4.38"
web-sys = "0.3.65"
yew-agent = "0.2.0"
