CREATE TABLE CHATTER (
	id SERIAL PRIMARY KEY,
	login VARCHAR NOT NULL UNIQUE,
	password VARCHAR NOT NULL,
	is_authorized BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	name VARCHAR NOT NULL,
	pfp VARCHAR
);
