-- Add up migration script here
CREATE TABLE PROCESS_KIND (
    id SERIAL PRIMARY KEY,
    name TEXT
);


INSERT INTO PROCESS_KIND(id, name) VALUES
(1, 'LoggedUsers'),
(2, 'MessagesSeen');

ALTER TABLE PROCESS_REPORT 
DROP COLUMN PROCESS_KIND,
ADD COLUMN PROCESS_ID INTEGER NOT NULL,
ADD CONSTRAINT fk_process_id_process_kind FOREIGN KEY(PROCESS_ID) REFERENCES PROCESS_KIND(ID) ON DELETE CASCADE ON UPDATE CASCADE; 