[package]
name = "toast_service"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0.192", features = ["derive"] }
wasm-bindgen = "0.2.88"
yew-agent = "0.2.0"
