name: Docker images

on:
  push:
    branches: [ "automate_builds" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extra steps to have it working with github
        run: |
          docker-compose build --parallel
