name: Docker images build

on:
  push:
    branches: [ "automate_builds" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install docker compose 
        run: sudo apt-get update; sudo apt-get install docker-compose -y

      - name: Extra steps to have it working with github
        run: docker-compose build --parallel
