name: Docker images build

on:
  push:
    branches: [ "automate_builds" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install docker compose 
        run: sudo apt-get update; sudo apt-get install docker-compose -y
      - name: Cat file
        run: cat ./docker-compose.yml
      - name: Build project
        run: docker-compose build --parallel
        working-directory: ./