name: Docker images build

on:
  push:
    branches: [ "automate_builds" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo dockerhub login
        env:
          DOCKERHUB_LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
        run: echo ${#DOCKERHUB_LOGIN}
      - name: DockerHub login
        env:
          LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo $PASSWORD | docker login -u $LOGIN --password-stdin
      - name: Install docker compose 
        run: sudo apt-get update; sudo apt-get install docker-compose -y
      - name: Build project
        run: docker-compose build --parallel
        working-directory: ./
      - name: Push image
        run: docker-compose push
        working-directory: ./